default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

production:
  <<: *default
  adapter: postgresql
  username: grail
  database: grail_production
  password: <%= ENV['GRAIL_DATABASE_PASSWORD'] %>